In [2]:
import numpy as np

In [3]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2,3],[4,3]])

/tmp/ipykernel_84/964258125.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3],[4,3]])


array([list([1, 2, 3]), list([4, 3])], dtype=object)

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a=[2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b=np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4]])

In [13]:
a=np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c=a

In [16]:
c

array([1, 2, 3, 4])

In [17]:
c[0]=100

In [18]:
c

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d=np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a[1]=500

In [23]:
a

array([100, 500,   3,   4])

In [24]:
d

array([100,   2,   3,   4])

In [25]:
c

array([100, 500,   3,   4])

In [26]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
iterable=(i*i for i in range(5))

In [29]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
np.fromstring('234 442',sep=' ')

array([234., 442.])

In [31]:
np.fromstring('4, 2',sep=' ,')

array([4., 2.])

In [32]:
#Numpy data type

In [33]:
l=[2,3,4,5,6]

In [34]:
ar=np.array(l)

In [35]:
ar

array([2, 3, 4, 5, 6])

In [36]:
ar.ndim

1

In [37]:
ar2 = np.array([[2, 4, 5, 6, 7], [1, 4, 5, 6, 0]])

In [38]:
ar2

array([[2, 4, 5, 6, 7],
       [1, 4, 5, 6, 0]])

In [39]:
ar2.ndim

2

In [40]:
ar.size

5

In [41]:
ar2.size

10

In [42]:
ar.shape

(5,)

In [43]:
ar2.shape

(2, 5)

In [44]:
ar.dtype

dtype('int64')

In [45]:
ar2.dtype

dtype('int64')

In [46]:
ar22 = np.array([(1, 2, 3, 4, 5), (34, 5, 56,0, 6)])

In [47]:
ar22

array([[ 1,  2,  3,  4,  5],
       [34,  5, 56,  0,  6]])

In [48]:
ar22.dtype

dtype('int64')

In [49]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [50]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [51]:
list(np.arange(2.3,5.6,.4))

[2.3,
 2.6999999999999997,
 3.0999999999999996,
 3.4999999999999996,
 3.8999999999999995,
 4.299999999999999,
 4.699999999999999,
 5.1,
 5.499999999999999]

In [52]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
np.zeros((3,4,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [57]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
on =np.ones((2,3,2))

In [59]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [60]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [61]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [64]:
np.logspace(2,4,10, base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [65]:
arr=np.random.randn(3,4)

In [66]:
import pandas as pd

In [67]:
pd.DataFrame(arr)

0         1         2         3
0 -1.240546  0.125625 -0.465072  0.099560
1 -0.864840  0.807145  0.852200  0.079035
2 -1.555551  0.847637 -0.746530  0.081303

In [68]:
np.random.randn(3,4)

array([[ 0.69752764,  0.98737605, -0.09448615, -0.14918488],
       [ 0.40381927, -0.00463635,  0.47606191,  0.63888335],
       [-1.26957073,  0.09024633, -1.20146402,  0.56667679]])

In [69]:
arr1=np.random.randint(1,110,(30,40))

In [70]:
arr1

array([[ 17,  67,  45, ...,  60,  48,  23],
       [  1,  67, 103, ...,  20,  66,  63],
       [ 14,  37,  62, ...,  10,  91,  54],
       ...,
       [ 83,  65,  40, ...,  96,  31, 103],
       [ 42,  57,  28, ...,  59,  70,   5],
       [ 99,  53, 108, ...,  47,  35, 102]])

In [71]:
pd.DataFrame(arr1)

0    1    2    3    4    5    6    7    8    9   ...   30   31  32   33  \
0    17   67   45   69  104   59   10   67   66   71  ...  107   68  78   13   
1     1   67  103   33   12   39   62    3   63   38  ...   35  108  55   63   
2    14   37   62   29   64   57   26   79   36  106  ...   29   84  21   88   
3    85   32   29   11   88   82    7   21   14   32  ...   44    4  83   34   
4    29   42   86   62   96   80   48   13  103   62  ...   83    9  29   69   
5    76  106   77   31   17   43   51  100    9   34  ...   34   30  43   81   
6    20   32   34   37   29  100  104   94   30  103  ...    8   94  15   44   
7    83   82   77   41   57   15   41   73  104   84  ...    4   82  44   71   
8    47   62   90   37   83   72   77   25   72   69  ...   90  108  87  107   
9    45   73  100   86   79   53   20   76   77   34  ...   24   87  80  102   
10   26    3   31   95   16   62   79   67   23   91  ...   61   72  90   25   
11   28   83   81    3   80   62   29   52    9  106  ...   64   42   7   24   
12   75   29   45   71   79    9    1   55   82   20  ...   25   96  53   84   
13   80    1   21   79   36   98   55   56   77   36  ...  101  100  44   18   
14    4    2   13  102   87   85   21   83   89   34  ...   90   27  45   46   
15   96   55    1   79   30   75   49   70   71  101  ...    5   33   4   76   
16  102   51   65   85    7   97   62   14   43   30  ...   90   24   5   52   
17   85    8   12   28   50   92   60   17   69   32  ...   53  101  41   73   
18   25   12   52   97   51   86   81   75   40   73  ...   56   20   7   79   
19   18   64   12   86   70   99   28   79   49   42  ...   63   26  14   19   
20   82   28   23   32   44   56  100   74   19   74  ...   98   44  39    2   
21   50   66   72   94   66  102   66   23  103    9  ...   17   81  34   40   
22   47   18   99    6   20   34   54   31    9   80  ...   31   48  89   68   
23    9   73    2  105   49   16    6   58   27   10  ...   95   56   3    3   
24  109   76    3   78   89   50   12   12   40  108  ...   32   55   6   41   
25   78    7   62   47   63   98   85   82   33   43  ...   24    6  85   81   
26   87   14   77   59   16   37    1   31   71   50  ...  108   97  90   30   
27   83   65   40   24   77   15   55  106  100   50  ...   27   60  28   58   
28   42   57   28   70   23   93   22   89   12    2  ...   15   95  21   24   
29   99   53  108    5   83   14    7   29   56   13  ...    4   58  45   77   

     34   35   36   37   38   39  
0    97   16   54   60   48   23  
1    32   16   95   20   66   63  
2    55   57   31   10   91   54  
3    45   98   83   46   59   97  
4    26  106   98   25   29   83  
5    24   90   13    2  109   75  
6    40   44   33   25  102   94  
7   105  103   90   43   90   79  
8    81   26   37   35  106   49  
9    13    8  108  107   66    6  
10   76   76   93   10   26   64  
11  107    2   41   61   54   15  
12   88   98   90   48   57   71  
13   36  107  109   76  102   17  
14    7   18   62   91   80   76  
15  107  103  107   72  101   70  
16   13   32   77   69   44   18  
17  109   32   36   94   94   90  
18   99    4   69   70   79   44  
19   13   41   97   19   40   60  
20   57  108   15    7   37   89  
21    2   75   82  108   57  108  
22   19   77   34   23   63  107  
23   34  101   39   39   74   69  
24   20   70   66   68    4   22  
25   66   48   56  100  108   87  
26  109   23   29   77   93   81  
27   94    5   42   96   31  103  
28   22    9   70   59   70    5  
29   88   70   16   47   35  102  

[30 rows x 40 columns]

In [72]:
pd.DataFrame(arr1).to_csv('test.csv')

In [73]:
arr=np.random.rand(3,4)

In [74]:
arr

array([[0.28383121, 0.04963134, 0.25319725, 0.90310128],
       [0.98361303, 0.44872222, 0.86288818, 0.12981357],
       [0.8095114 , 0.28475779, 0.70321215, 0.71943936]])

In [75]:
arr2=arr.reshape(6,2)

In [76]:
arr2

array([[0.28383121, 0.04963134],
       [0.25319725, 0.90310128],
       [0.98361303, 0.44872222],
       [0.86288818, 0.12981357],
       [0.8095114 , 0.28475779],
       [0.70321215, 0.71943936]])

In [77]:
arr2[1]

array([0.25319725, 0.90310128])

In [78]:
arr2[1][1]

0.9031012796361163

In [79]:
arr2[2:5,0]

array([0.98361303, 0.86288818, 0.8095114 ])

In [80]:
arr2[2:5,1]

array([0.44872222, 0.12981357, 0.28475779])

In [85]:
arr=np.random.randint(1,100,(5,5))

In [86]:
arr

array([[75, 18, 26, 86, 10],
       [51, 62, 92, 31, 67],
       [43, 47, 38, 69, 12],
       [43, 55, 71, 36, 21],
       [36, 32, 46, 92, 80]])

In [87]:
arr>50

array([[ True, False, False,  True, False],
       [ True,  True,  True, False,  True],
       [False, False, False,  True, False],
       [False,  True,  True, False, False],
       [False, False, False,  True,  True]])

In [88]:
arr[arr>50]

array([75, 86, 51, 62, 92, 67, 69, 55, 71, 92, 80])

In [89]:
arr

array([[75, 18, 26, 86, 10],
       [51, 62, 92, 31, 67],
       [43, 47, 38, 69, 12],
       [43, 55, 71, 36, 21],
       [36, 32, 46, 92, 80]])

In [90]:
arr[2:4,[1,2]]

array([[47, 38],
       [55, 71]])

In [91]:
arr[0][0]

75

In [92]:
arr[0][0]=500

In [93]:
arr

array([[500,  18,  26,  86,  10],
       [ 51,  62,  92,  31,  67],
       [ 43,  47,  38,  69,  12],
       [ 43,  55,  71,  36,  21],
       [ 36,  32,  46,  92,  80]])

In [94]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [95]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [2, 1, 2]])

In [96]:
arr2

array([[2, 1, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [97]:
arr1+arr2

array([[3, 3, 3],
       [3, 4, 4],
       [3, 3, 4]])

In [98]:
arr1*arr2

array([[2, 2, 2],
       [2, 4, 4],
       [2, 2, 4]])

In [99]:
arr1/arr2

array([[0.5, 2. , 2. ],
       [0.5, 1. , 1. ],
       [2. , 0.5, 1. ]])

In [100]:
arr1@arr2

array([[8, 9, 9],
       [8, 9, 9],
       [8, 8, 8]])

In [101]:
arr1/0

/tmp/ipykernel_84/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [102]:
arr1+100

array([[101, 102, 102],
       [101, 102, 102],
       [102, 101, 102]])

In [103]:
arr1**2

array([[1, 4, 4],
       [1, 4, 4],
       [4, 1, 4]])

In [104]:
#Broadcostig

In [105]:
arr=np.zeros((4,4))

In [106]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
row=np.array([1,2,3,4])

In [108]:
row

array([1, 2, 3, 4])

In [109]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [110]:
row.T

array([1, 2, 3, 4])

In [114]:
col=np.array([[1,2,3,4]])

In [115]:
col

array([[1, 2, 3, 4]])

In [118]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [119]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [120]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
arr1=np.random.randint(1,4,(3,4))

In [123]:
arr1

array([[3, 1, 1, 2],
       [3, 2, 2, 1],
       [2, 3, 3, 1]])

In [124]:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.        , 1.41421356],
       [1.73205081, 1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.73205081, 1.73205081, 1.        ]])

In [125]:
np.exp(arr1)

array([[20.08553692,  2.71828183,  2.71828183,  7.3890561 ],
       [20.08553692,  7.3890561 ,  7.3890561 ,  2.71828183],
       [ 7.3890561 , 20.08553692, 20.08553692,  2.71828183]])

In [126]:
np.log10(arr1)

array([[0.47712125, 0.        , 0.        , 0.30103   ],
       [0.47712125, 0.30103   , 0.30103   , 0.        ],
       [0.30103   , 0.47712125, 0.47712125, 0.        ]])