In [1]:
#Sort,Search & Counting Functions

In [6]:
import numpy as np

In [7]:
arr=np.array([4,3,2,5,644,66,7,777])

In [8]:
arr

array([  4,   3,   2,   5, 644,  66,   7, 777])

In [9]:
np.sort(arr)

array([  2,   3,   4,   5,   7,  66, 644, 777])

In [11]:
np.searchsorted(arr,24)

4

In [12]:
arr1=np.array([0,345,0,0,0,32])

In [13]:
arr1

array([  0, 345,   0,   0,   0,  32])

In [14]:
np.count_nonzero(arr1)

2

In [15]:
arr

array([  4,   3,   2,   5, 644,  66,   7, 777])

In [16]:
np.where(arr>6)

(array([4, 5, 6, 7]),)

In [17]:
np.extract(arr>6,arr)

array([644,  66,   7, 777])

In [18]:
arr

array([  4,   3,   2,   5, 644,  66,   7, 777])

In [19]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   144115188075855872,
         360287970189639680, -8934578710749642752,  4755801206503243776,
         504403158265495552,   649362771271483392])

In [20]:
#copies & views

In [21]:
arr

array([  4,   3,   2,   5, 644,  66,   7, 777])

In [22]:
a=np.copy(arr)

In [23]:
a

array([  4,   3,   2,   5, 644,  66,   7, 777])

In [24]:
b=arr.view()

In [25]:
b

array([  4,   3,   2,   5, 644,  66,   7, 777])

In [26]:
arr

array([  4,   3,   2,   5, 644,  66,   7, 777])

In [27]:
b[0]=88

In [28]:
b

array([ 88,   3,   2,   5, 644,  66,   7, 777])

In [29]:
b[2]=100

In [30]:
b

array([ 88,   3, 100,   5, 644,  66,   7, 777])

In [31]:
# Matrix Libary

In [32]:
import numpy.matlib as nm

In [33]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [34]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [36]:
#Liner Algebra

In [37]:
arr1=np.random.randint([[2,3],[4,5]])

In [39]:
arr2=np.random.randint([[5,3],[2,5]])

In [40]:
np.dot(arr1,arr2)

array([[4, 6],
       [0, 4]])

In [41]:
arr1@arr2

array([[4, 6],
       [0, 4]])