In [1]:
#Array Manipulation

In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,10,(3,4))

In [4]:
arr

array([[8, 4, 6, 3],
       [3, 7, 5, 1],
       [4, 8, 9, 3]])

In [5]:
arr.reshape(6,2)

array([[8, 4],
       [6, 3],
       [3, 7],
       [5, 1],
       [4, 8],
       [9, 3]])

In [7]:
arr.T

array([[8, 3, 4],
       [4, 7, 8],
       [6, 5, 9],
       [3, 1, 3]])

In [8]:
arr.flatten()

array([8, 4, 6, 3, 3, 7, 5, 1, 4, 8, 9, 3])

In [9]:
arr1=np.array([1,2,3,4])

In [10]:
arr1.ndim

1

In [11]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4]])

In [13]:
arr

array([[8, 4, 6, 3],
       [3, 7, 5, 1],
       [4, 8, 9, 3]])

In [14]:
np.squeeze(arr)

array([[8, 4, 6, 3],
       [3, 7, 5, 1],
       [4, 8, 9, 3]])

In [15]:
data=np.array([[1],[2],[3]])

In [16]:
data

array([[1],
       [2],
       [3]])

In [17]:
np.squeeze(data)

array([1, 2, 3])

In [18]:
arr1

array([1, 2, 3, 4])

In [19]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [21]:
np.roll(arr1,2)

array([3, 4, 1, 2])

In [22]:
arr1

array([1, 2, 3, 4])

In [23]:
np.roll(arr1,3)

array([2, 3, 4, 1])

In [24]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
#Binary Operations

In [26]:
arr1=np.random.randint(1,10,(3,4))

In [29]:
arr2=np.random.randint(1,10,(3,4))

In [30]:
arr1

array([[2, 8, 4, 3],
       [6, 2, 6, 2],
       [8, 9, 9, 3]])

In [31]:
arr2

array([[7, 9, 7, 5],
       [7, 8, 6, 6],
       [2, 2, 6, 2]])

In [32]:
arr1+arr2

array([[ 9, 17, 11,  8],
       [13, 10, 12,  8],
       [10, 11, 15,  5]])

In [33]:
arr1-arr2

array([[-5, -1, -3, -2],
       [-1, -6,  0, -4],
       [ 6,  7,  3,  1]])

In [34]:
arr1/arr2

array([[0.28571429, 0.88888889, 0.57142857, 0.6       ],
       [0.85714286, 0.25      , 1.        , 0.33333333],
       [4.        , 4.5       , 1.5       , 1.5       ]])

In [35]:
arr1%arr2

array([[2, 8, 4, 3],
       [6, 2, 0, 2],
       [0, 1, 3, 1]])

In [36]:
arr1**arr2

array([[      128, 134217728,     16384,       243],
       [   279936,       256,     46656,        64],
       [       64,        81,    531441,         9]])

In [37]:
arr1&arr2

array([[2, 8, 4, 1],
       [6, 0, 6, 2],
       [0, 0, 0, 2]])

In [39]:
arr1|arr2

array([[ 7,  9,  7,  7],
       [ 7, 10,  6,  6],
       [10, 11, 15,  3]])

In [40]:
arr1>arr2

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [41]:
#String function

In [42]:
arr=np.array(['mahesh','yadav'])

In [43]:
arr


array(['mahesh', 'yadav'], dtype='<U6')

In [44]:
np.char.upper(arr)

array(['MAHESH', 'YADAV'], dtype='<U6')

In [45]:
np.char.title(arr)

array(['Mahesh', 'Yadav'], dtype='<U6')

In [46]:
np.char.capitalize(arr)

array(['Mahesh', 'Yadav'], dtype='<U6')

In [49]:
#Mathematical Functions

In [50]:
arr1

array([[2, 8, 4, 3],
       [6, 2, 6, 2],
       [8, 9, 9, 3]])

In [51]:
np.sin(arr1)

array([[ 0.90929743,  0.98935825, -0.7568025 ,  0.14112001],
       [-0.2794155 ,  0.90929743, -0.2794155 ,  0.90929743],
       [ 0.98935825,  0.41211849,  0.41211849,  0.14112001]])

In [52]:
np.cos(arr1)

array([[-0.41614684, -0.14550003, -0.65364362, -0.9899925 ],
       [ 0.96017029, -0.41614684,  0.96017029, -0.41614684],
       [-0.14550003, -0.91113026, -0.91113026, -0.9899925 ]])

In [53]:
np.tan(arr1)

array([[-2.18503986, -6.79971146,  1.15782128, -0.14254654],
       [-0.29100619, -2.18503986, -0.29100619, -2.18503986],
       [-6.79971146, -0.45231566, -0.45231566, -0.14254654]])

In [54]:
np.log10(arr1)

array([[0.30103   , 0.90308999, 0.60205999, 0.47712125],
       [0.77815125, 0.30103   , 0.77815125, 0.30103   ],
       [0.90308999, 0.95424251, 0.95424251, 0.47712125]])

In [55]:
np.exp(arr1)

array([[7.38905610e+00, 2.98095799e+03, 5.45981500e+01, 2.00855369e+01],
       [4.03428793e+02, 7.38905610e+00, 4.03428793e+02, 7.38905610e+00],
       [2.98095799e+03, 8.10308393e+03, 8.10308393e+03, 2.00855369e+01]])

In [56]:
np.sqrt(arr1)

array([[1.41421356, 2.82842712, 2.        , 1.73205081],
       [2.44948974, 1.41421356, 2.44948974, 1.41421356],
       [2.82842712, 3.        , 3.        , 1.73205081]])

In [58]:
np.power(arr1,2)

array([[ 4, 64, 16,  9],
       [36,  4, 36,  4],
       [64, 81, 81,  9]])

In [59]:
np.mean(arr1)

5.166666666666667

In [61]:
np.median(arr1)

5.0

In [62]:
np.std(arr1
      )

2.7028791233711424

In [63]:
np.var(arr1)

7.305555555555556

In [64]:
np.min(arr1)

2

In [65]:
np.max(arr1)

9